version: '2'
services:
  db:
    image: postgres
    volumes:
    - data:/var/lib/postgresql/db-data
    restart: always

  app:
    env_file: .env
    build: .
    command: bundle exec rails server --environment production -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db


  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./_log/nginx:/var/log/nginx
    volumes_from:
      - app
    depends_on:
      - app
    ports:
      - 80:80

volumes:
  data:
    external: false
